include: package:pedantic/analysis_options.1.11.0.yaml

analyzer:
  exclude: ["build/**", "**/*.g.dart"]
  errors:
    invalid_assignment: error
    missing_return: error
    dead_code: error
    avoid_init_to_null: info
    empty_catches: error
    await_only_futures: error
    avoid_print: warning
    always_declare_return_types: error
    always_specify_types: warning
    avoid_return_types_on_setters: info
    unawaited_futures: error
    curly_braces_in_flow_control_structures: ignore
strong-mode:
  implicit-dynamic: true

linter:
  rules:
    sort_child_properties_last: false
    avoid_empty_else: true
    avoid_init_to_null: true
    avoid_relative_lib_imports: true
    avoid_return_types_on_setters: true
    avoid_shadowing_type_parameters: true
    avoid_types_as_parameter_names: true
    curly_braces_in_flow_control_structures: true
    empty_catches: true
    empty_constructor_bodies: true
    library_names: true
    library_prefixes: true
    no_duplicate_case_values: true
    null_closures: true
    prefer_contains: true
    prefer_equal_for_default_values: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_iterable_whereType: true
    recursive_getters: true
    slash_for_doc_comments: true
    type_init_formals: true
    unawaited_futures: true
    unnecessary_const: true
    unnecessary_new: true
    unnecessary_null_in_if_null_operators: true
    unrelated_type_equality_checks: true
    use_rethrow_when_possible: true
    valid_regexps: true
    await_only_futures: true
    prefer_single_quotes: false
    prefer_if_null_operators: true
